INSERT INTO genres (genre) VALUES
('Josei'),
('Seinen'),
('Shoujo'),
('Shounen'),
('GL'),
('BL'),
('Lolicon'),
('Shotacon'),
('Hentai'),
('Smut'),
('Borderline H'),
('Adult'),
('Mature'),
('Ecchi'),
('Doujinshi'),
('4-Koma'),
('Anthology'),
('Harlequin'),
('Webtoon'),
('Old-Style'),
('Award'),
('Cancel'),
('Rushed'),
('European'),
('Asian'),
('isekai'),
('Reverse isekai'),
('Time Rewind'),
('Villainess'),
('Revenge'),
('Modern'),
('Childhood F.'),
('Con. Marr.'),
('Arranged Marr.'),
('Sensei'),
('Age Gap'),
('Office'),
('Boss-Sub'),
('Showbiz'),
('Action'),
('Adventure'),
('Comedy'),
('Drama'),
('Fantasy'),
('Gender Bender'),
('Harem'),
('Reverse Harem'),
('Historical'),
('Horror'),
('Martial Arts'),
('Mecha'),
('Mystery'),
('Psychological'),
('Romance'),
('School Life'),
('Sci-fi'),
('Slice of Life'),
('Sports'),
('Supernatural'),
('Tragedy'),
('Incest'),
('Yandere'),
('Toxic Rel.');