INSERT OR IGNORE INTO genres (genre) VALUES
('Josei'),
('Seinen'),
('Shoujo'),
('Shounen'),
('GL'),
('BL'),
('Lolicon'),
('Shotacon'),
('Hentai'),
('Smut'),
('Borderline H'),
('Adult'),
('Mature'),
('Ecchi'),
('Doujinshi'),
('4-Koma'),
('Anthology'),
('Harlequin'),
('Webtoon'),
('Old-Style'),
('Award'),
('Cancel'),
('Rushed'),
('European'),
('Asian'),
('isekai'),
('Reverse isekai'),
('Time Rewind'),
('Villainess'),
('Revenge'),
('Modern'),
('Childhood F.'),
('Con. Marr.'),
('Arranged Marr.'),
('Sensei'),
('Age Gap'),
('Office'),
('Boss-Sub'),
('Showbiz'),
('Action'),
('Adventure'),
('Comedy'),
('Drama'),
('Fantasy'),
('Gender Bender'),
('Harem'),
('Reverse Harem'),
('Historical'),
('Horror'),
('Martial Arts'),
('Mecha'),
('Mystery'),
('Psychological'),
('Romance'),
('School Life'),
('Sci-fi'),
('Slice of Life'),
('Sports'),
('Supernatural'),
('Tragedy'),
('Incest'),
('Yandere'),
('Toxic Rel.');

INSERT OR IGNORE INTO settings VALUES
('main_rating', 'mu'),
('title_languages', 'en'),
('mu_integration', 0),
('mu_username', NULL),
('mu_password', NULL),
('mu_list_plan_to_read', 1),
('mu_list_reading', 0),
('mu_list_completed',2),
('mu_list_one-shots', 101),
('mu_list_dropped', 3),
('mu_list_on_hold', 4),
('mu_list_ongoing', 102),
('dex_integration', 0),
('dex_integration_forced', 0),
('dex_username', NULL),
('dex_password', NULL),
('dex_client_id', NULL),
('dex_secret', NULL),
('mal_integration', 0);