name: Generate Static Redoc page

on:
  push:
    paths:
      - 'static/openapi.yaml'

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build docs
        run: npx @redocly/cli build-docs static/openapi.yaml -o static/redoc.html --theme.openapi.downloadDefinitionUrl=/api/openapi.yaml

      - name: Commit docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add static/redoc.html
          git commit -m "chore: update redoc.html" || echo "No changes to commit"
          git push
